### ISSUE TITLE
Config file for RbxRefresh projects

### ISSUE THREAD

**Issue by LPGhatguy** [osyrisrblx/RbxRefresh#10]
I have a plugin that operates very similarly: https://github.com/LPGhatguy/rbxfs

I don't want to use my plugin anymore, but it provides a configuration system that lets me nail some options down per-project.

Specifically, I want to configure file names and how they map to the different Roblox script types!

**Comment by osyrisrblx** [comment]
This seems like a good idea. I've already started doing this. You can create a file called ".rbxrefreshrc" inside your Project directory and it will read the config options from there as JSON. The only current allowed option is "placeId" which can be a string, number, or array of numbers. This prevents you from accidentally smashing two code bases together with RbxRefresh. (Omitting the placeId field prevents this guard).

If you have any other config options, I'd love to hear them.
