### ISSUE TITLE
Not an issue, but a resource

### ISSUE THREAD

**Issue by vocksel** [osyrisrblx/RbxRefresh#3]
Hi guys, I actually made something that's really similar to where this project is heading. It's called Studio Bridge. It does the whole syncing from fs to Studio using a web server and plugin.

I figured it'd be helpful to have a similar resource to look to while developing. I split the project up into 3 repos. One for docs, the server, and the plugin. If you want to take a look here are the links:

- [Main repo (docs)](https://github.com/vocksel/studio-bridge)
- [Server/CLI](https://github.com/vocksel/studio-bridge-cli)
- [Plugin](https://github.com/vocksel/studio-bridge-plugin)

Feel free to close this whenever you like, just wanted to bring it to your attention. Good luck! I'm really looking forward to seeing where this all goes. :D

**Comment by spotco** [comment]
did you ever get the reverse direction (studio to FS sync) working?

**Comment by osyrisrblx** [comment]
Wow that looks awesome.
Definitely a good idea to use npm for installation. Might end up doing that for RbxRefresh.

**Comment by vocksel** [comment]
@spotco I didn't. That wasn't something I planned on implementing. [RbxSync](https://github.com/evaera/RbxSync) can do that though. Take a look through the repo if you haven't already. It's got some great ideas of its own (love that it lives in the system tray)

@osyrisrblx Thanks! I hope it'll be helpful as you guys continue developing RbxRefresh.
