### ISSUE TITLE
Shebang issue on arch linux

### ISSUE THREAD

**Issue by cipharius** [osyrisrblx/RbxRefresh#7]
When I try to run `rbxrefresh` after installing it with npm, I get the following error:
`/usr/bin/env: ‘node\r’: No such file or directory`

Figured that it's due to the trailing `\r` character, so decided to convert the `rbxrefresh` to unix line endings, which fixes this issue.

Not sure what's the best action here, besides using unix style line endings.

**Comment by osyrisrblx** [comment]
Odd, thought I fixed this for OSX. Seems to be difficult to maintain line endings properly.

... why are you using RbxRefresh on Linux?

**Comment by cipharius** [comment]
Roblox studio works just fine with latest wine git version and most of the time I don't have any other system available.
