### ISSUE TITLE
Occasionally updates don't reach plugin

### ISSUE THREAD

**Issue by cipharius** [osyrisrblx/RbxRefresh#8]
Sometimes the file update commands fail to reach roblox studio plugin. The `rbxrefresh` process detects file change just fine.

If I stop the `rbxrefresh` process and run it again, plugin succesfully catches the full update command and other succeeding commands until it breaks again.

I don't have the details on how exactly to replicate this, but when I'll have a time, I'll try to see if there is certain pattern to this behavior and see what could casue it.

Edit: So many times when this occurs, I get this error message after stopping the `rbxrefresh`:
`[RbxRefresh] Ending because: CURL error (curl_easy_perform): Server returned nothing (no headers, no data) (52)`.

Might be just due to me killing `rbxrefresh`, but at least some clue.

**Comment by osyrisrblx** [comment]
I believe I've fixed this.
